### ISSUE TITLE
How to program icehat?

### ISSUE THREAD

**Issue by liubenyuan** [emeb/icehat#1]
Hi, Thanks for your project icehat.

I find that you do not have any jtag headers (sorry I just moved from Xilinx), how could I program icehat?

Or, can I add one FTDI pins to icehat?

**Comment by emeb** [comment]
Lattice FPGAs do not require (or support) JTAG programming - they can 
only be programmed via the SPI interface. On the Icehat the SPI 
interface is connected to the Raspberry Pi SPI port so the FPGA can be 
configured via programs running on the Raspberry Pi. In the github 
repository I have provided source code for an application that can do 
this, as well as a library of code that can be added to other applications.

**Comment by liubenyuan** [comment]
Thanks ! Does ice40lp4k support LVDS input/output ? In
```
Using Differential I/O (LVDS, Sub-LVDS)
in iCE40 LP/HX Devices
```
~~It says that ice40lp4k has 20 lvds pairs, where are they ? I do not find any pins named as `_P` or `_N` as for Xilinx. I do not know whether this chip support long rang LVDS transmission.~~

Updated. Sorry lvds is only supported in `ice40lp4k` while not in `icp5lp4k` ...

**Comment by emeb** [comment]
Lattice FPGAs do not require (or support) JTAG programming - they can only be programmed via the SPI interface. On the Icehat the SPI interface is connected to the Raspberry Pi SPI port so the FPGA can be configured via programs running on the Raspberry Pi. In the github repository I have provided source code for an application that can do this, as well as a library of code that can be added to other applications.

**Comment by emeb** [comment]
Icehat does not use an LP/HX device - it is an Ultra device. Please see the data sheet for this family here:

http://www.latticesemi.com/view_document?document_id=51968

According to that document, LVDS is not specifically supported. It mentions that some pins provide differential input but then does not list which pins. The following spreadsheet document provides information on differential pairs for the device used on Icehat:

http://www.latticesemi.com/view_document?document_id=50697

**Comment by liubenyuan** [comment]
Thanks!
